services:
  everstudy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    command: ["npm", "run", "dev"]
volumes:
  node_modules:
    driver: local
    name: node_modules
